### ISSUE TITLE
Isolate Bandwidth Sharing Model

### ISSUE THREAD

**Issue by csegarragonz** [miguelammatos/Kollaps#11]
Identify the code segments where the current BW Sharing Model is implemented and enforced, isolate it and showcase the implementation by implementing a dumb BW Sharing Model.

**To-Do**
1. [ ] Identify the BW Sharing Implementation in the source code.
2. [ ] Identify the BW Sharing enforcement point.
3. [ ] Isolate the component.
4. [ ] Implement a dumb alternative.
