### ISSUE TITLE
Include Bandwidth Sharing Model in the Topology Description Language

### ISSUE THREAD

**Issue by csegarragonz** [miguelammatos/Kollaps#12]
Propose a way to include the Bandwidth Sharing Model in the Topology Description Language:
+ Should it be done on a per-link basis? How would this affect the graph collapsing strategy?
+ Should it be on a per-topology basis? Then we might only be able to simulate a smaller variety of architectures.

Implement, test, and assess the performance on the solution on some simple topologies.

**To-Do**
1. [ ] Proposal for how to include BWS models in the Topology Description Language.
2. [ ] Implement the required changes in the DSL.
3. [ ] Test the solution in a variety of topologies.
