### ISSUE TITLE
Implement Alternative Bandwidth Sharing Models

### ISSUE THREAD

**Issue by csegarragonz** [miguelammatos/Kollaps#13]
Shortlist, implement, evaluate, and compare different bandwidth sharing models. This issue has a lot of implementation but a lot of evaluation and reporting as well.

**To-Do**
1. [ ] Shortlist a variety of BW Sharing Models (see #10 )
2. [ ] Implement the different BW Sharing Models
3. [ ] Perform an exhaustive comparison. Which models are more accurate for different topologies?
    1. [ ] Choose the different topologies.
    2. [ ] Choose the metrics to be analyzed.
    3. [ ] Run all the experiments.
    4. [ ] Present the results.
